/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import characters.Human;
import characters.Player;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * @author Мария
 */
public class JFrames extends javax.swing.JFrame {

    Game game = new Game();
    Human human = null;
    Player enemy = null;
    Items[] items = new Items[3];
    String nameButton = "";


    /**
     * Creates new form JFrame
     */
    public JFrames() {
        initComponents();
        try {
            game.ReadFromExcel();
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.WriteToTable(jTableResult);

        itemsButtonGroup.add(jRadioFirstItem);
        itemsButtonGroup.add(jRadioSecondItem);
        itemsButtonGroup.add(jRadioThirdItem);

        items[0] = new Items("Малое зелье лечение", 0);
        items[1] = new Items("Большое зелье лечение", 0);
        items[2] = new Items("Крест возрождения", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGamingFrame = new javax.swing.JFrame();
        jPanelGameplay = new javax.swing.JPanel();
        jLabelPlayerIcon = new javax.swing.JLabel();
        jButtonAttack = new javax.swing.JButton();
        jButtonDefence = new javax.swing.JButton();
        jPlayerHPBar = new javax.swing.JProgressBar();
        jEnemyImage = new javax.swing.JLabel();
        jEnemyHPBar = new javax.swing.JProgressBar();
        jEnemyName = new javax.swing.JLabel();
        jLabelEnemyDamage = new javax.swing.JLabel();
        jLabelPlayerDamage = new javax.swing.JLabel();
        jLabelPlayerDamageValue = new javax.swing.JLabel();
        jEnemyDamage = new javax.swing.JLabel();
        jPlayerLevel = new javax.swing.JLabel();
        jLabelFight = new javax.swing.JLabel();
        jPlayerHealth = new javax.swing.JLabel();
        jEnemyHealth = new javax.swing.JLabel();
        jLabelExperience = new javax.swing.JLabel();
        jLabelPoints = new javax.swing.JLabel();
        jPlayerExperience = new javax.swing.JLabel();
        jPlayerPoints = new javax.swing.JLabel();
        jEnemyLevel = new javax.swing.JLabel();
        jTurnNow = new javax.swing.JLabel();
        jResult = new javax.swing.JLabel();
        jLabelPlayerName = new javax.swing.JLabel();
        jLabelStun = new javax.swing.JLabel();
        jButtonItems = new javax.swing.JButton();
        jDialogWinner = new javax.swing.JDialog();
        jPanelWin = new javax.swing.JPanel();
        jLabelWinner = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        jDialogFinishName = new javax.swing.JDialog();
        jPanelFinish = new javax.swing.JPanel();
        jLabelPlayerWin = new javax.swing.JLabel();
        jTextFieldPlayerName = new javax.swing.JTextField();
        jLabelSetPlayerName = new javax.swing.JLabel();
        jLabelSetNameForTable = new javax.swing.JLabel();
        jButtonFinishGame = new javax.swing.JButton();
        jDialogTableRecords = new javax.swing.JDialog();
        jPanelRecordsTable = new javax.swing.JPanel();
        jLabelRecordsTable = new javax.swing.JLabel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        jButtonCloseRecordsTable = new javax.swing.JButton();
        jDialogTop10 = new javax.swing.JDialog();
        jPanelWinResult = new javax.swing.JPanel();
        jLabelWinGame = new javax.swing.JLabel();
        jLabelLittleResult = new javax.swing.JLabel();
        jButtonEndGame = new javax.swing.JButton();
        jDialogItems = new javax.swing.JDialog();
        jPanelItems = new javax.swing.JPanel();
        jLabelBagItems = new javax.swing.JLabel();
        jRadioFirstItem = new javax.swing.JRadioButton();
        jRadioSecondItem = new javax.swing.JRadioButton();
        jRadioThirdItem = new javax.swing.JRadioButton();
        jButtonUseItem = new javax.swing.JButton();
        itemsButtonGroup = new javax.swing.ButtonGroup();
        jDialogCantUseItem = new javax.swing.JDialog();
        jPanelCantUseItem = new javax.swing.JPanel();
        jLabelCantUseItem = new javax.swing.JLabel();
        jLabelCantUseItemContinue = new javax.swing.JLabel();
        jButtonCantUseItemOK = new javax.swing.JButton();
        jPanelStart = new javax.swing.JPanel();
        jLabelGame = new javax.swing.JLabel();
        jButtonStartGame = new javax.swing.JButton();
        jButtonShowRecords = new javax.swing.JButton();
        jLabelGameImage = new javax.swing.JLabel();

        jLabelCountLocation = new javax.swing.JLabel();
        jButtonChoseLocation = new javax.swing.JButton();
        jPanelChoseLocation = new javax.swing.JPanel();
        jTextFieldCountLocation = new javax.swing.JTextField();
        jDialogChoseLocation = new javax.swing.JDialog();

        jPanelGameplay.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPlayerIcon.setIcon(new javax.swing.ImageIcon("src/main/resources/images/kitana.png")); // NOI18N

        jButtonAttack.setBackground(new java.awt.Color(255, 0, 0));
        jButtonAttack.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonAttack.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAttack.setText("Атаковать");
        jButtonAttack.addActionListener(this::jButtonAttack);

        jButtonDefence.setBackground(new java.awt.Color(255, 204, 0));
        jButtonDefence.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonDefence.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDefence.setText("Защититься");
        jButtonDefence.addActionListener(this::jButtonDefence);

        jPlayerHPBar.setBackground(new java.awt.Color(204, 204, 204));
        jPlayerHPBar.setForeground(new java.awt.Color(51, 255, 51));
        jPlayerHPBar.setMaximum(80);
        jPlayerHPBar.setMinimum(-1);

        jEnemyHPBar.setBackground(new java.awt.Color(204, 204, 204));
        jEnemyHPBar.setForeground(new java.awt.Color(0, 255, 0));
        jEnemyHPBar.setMinimum(-1);

        jEnemyName.setBackground(new java.awt.Color(0, 0, 0));
        jEnemyName.setFont(new java.awt.Font("Comic Sans MS", Font.ITALIC, 14)); // NOI18N

        jLabelEnemyDamage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnemyDamage.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jLabelEnemyDamage.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEnemyDamage.setText("Damage");

        jLabelPlayerDamage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPlayerDamage.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jLabelPlayerDamage.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPlayerDamage.setText("Damage");

        jLabelPlayerDamageValue.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPlayerDamageValue.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jLabelPlayerDamageValue.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPlayerDamageValue.setText("16");

        jEnemyDamage.setBackground(new java.awt.Color(255, 255, 255));
        jEnemyDamage.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jEnemyDamage.setForeground(new java.awt.Color(255, 0, 0));
        jEnemyDamage.setText("16");

        jPlayerLevel.setBackground(new java.awt.Color(255, 255, 255));
        jPlayerLevel.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 12)); // NOI18N
        jPlayerLevel.setForeground(new java.awt.Color(0, 0, 0));
        jPlayerLevel.setText("0 уровень");

        jLabelFight.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFight.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD | Font.ITALIC, 36)); // NOI18N
        jLabelFight.setForeground(new java.awt.Color(0, 0, 153));
        jLabelFight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFight.setText("FIGHT");
        jLabelFight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPlayerHealth.setBackground(new java.awt.Color(255, 255, 255));
        jPlayerHealth.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jPlayerHealth.setForeground(new java.awt.Color(102, 102, 102));
        jPlayerHealth.setText("80/80");

        jEnemyHealth.setBackground(new java.awt.Color(255, 255, 255));
        jEnemyHealth.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jEnemyHealth.setForeground(new java.awt.Color(102, 102, 102));
        jEnemyHealth.setText("80/80");

        jLabelExperience.setBackground(new java.awt.Color(255, 255, 255));
        jLabelExperience.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 18)); // NOI18N
        jLabelExperience.setForeground(new java.awt.Color(128, 92, 31));
        jLabelExperience.setText("experience");

        jLabelPoints.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPoints.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 18)); // NOI18N
        jLabelPoints.setForeground(new java.awt.Color(128, 92, 31));
        jLabelPoints.setText("points");

        jPlayerExperience.setBackground(new java.awt.Color(255, 255, 255));
        jPlayerExperience.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jPlayerExperience.setForeground(new java.awt.Color(113, 90, 16));
        jPlayerExperience.setText("0/40");

        jPlayerPoints.setBackground(new java.awt.Color(255, 255, 255));
        jPlayerPoints.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jPlayerPoints.setForeground(new java.awt.Color(113, 90, 16));
        jPlayerPoints.setText("00");

        jEnemyLevel.setBackground(new java.awt.Color(255, 255, 255));
        jEnemyLevel.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 12)); // NOI18N
        jEnemyLevel.setForeground(new java.awt.Color(0, 0, 0));
        jEnemyLevel.setText("1 уровень");

        jTurnNow.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 16)); // NOI18N
        jTurnNow.setForeground(new java.awt.Color(0, 0, 0));
        jTurnNow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jResult.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 12)); // NOI18N
        jResult.setForeground(new java.awt.Color(204, 0, 0));
        jResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelPlayerName.setFont(new java.awt.Font("Comic Sans MS", Font.ITALIC, 14)); // NOI18N
        jLabelPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlayerName.setText("Kitana");

        jLabelStun.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 16)); // NOI18N
        jLabelStun.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonItems.setBackground(new java.awt.Color(174, 183, 106));
        jButtonItems.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 12)); // NOI18N
        jButtonItems.setForeground(new java.awt.Color(0, 0, 0));
        jButtonItems.setText("Предметы");
        jButtonItems.addActionListener(this::jButtonItemsActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanelGameplay);
        jPanelGameplay.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jEnemyHealth)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(262, 262, 262)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabelFight, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelExperience))
                                                .addContainerGap())
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jEnemyHPBar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGap(92, 92, 92)
                                                                                                .addComponent(jLabelPoints))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGap(111, 111, 111)
                                                                                                .addComponent(jPlayerPoints)
                                                                                                .addGap(108, 108, 108)
                                                                                                .addComponent(jPlayerExperience))))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabelEnemyDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jEnemyDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(10, 10, 10)
                                                                                .addComponent(jEnemyName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jEnemyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(69, 69, 69)
                                                                                .addComponent(jTurnNow, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(26, 26, 26)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabelStun, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jButtonItems, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(46, 46, 46)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jPlayerLevel)
                                                                .addGap(26, 26, 26))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jPlayerHPBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jPlayerHealth))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabelPlayerDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabelPlayerDamageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(45, 45, 45))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabelPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(60, 60, 60))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabelPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(144, 144, 144))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jButtonAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(46, 46, 46)
                                                                .addComponent(jButtonDefence, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(68, 68, 68))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jEnemyLevel)
                                        .addContainerGap(854, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(21, Short.MAX_VALUE)
                                .addComponent(jLabelFight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPlayerHPBar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                        .addComponent(jEnemyHPBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jPlayerHealth))
                                                        .addComponent(jEnemyHealth, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelExperience)
                                                        .addComponent(jLabelPoints))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jPlayerExperience)
                                                        .addComponent(jPlayerPoints))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelPlayerDamage)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelEnemyDamage)
                                                .addComponent(jEnemyDamage)
                                                .addComponent(jLabelPlayerDamageValue)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jEnemyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jEnemyName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jPlayerLevel)
                                                                .addGap(7, 7, 7)
                                                                .addComponent(jLabelPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTurnNow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelStun, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButtonItems, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jButtonAttack, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                                                .addComponent(jButtonDefence, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                                                .addGap(14, 14, 14))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addComponent(jEnemyLevel)
                                        .addContainerGap(380, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jGamingFrame.getContentPane());
        jGamingFrame.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jPanelGameplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelGameplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelWin.setBackground(new java.awt.Color(179, 226, 217));

        jLabelWinner.setBackground(new java.awt.Color(204, 204, 204));
        jLabelWinner.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 42)); // NOI18N
        jLabelWinner.setForeground(new java.awt.Color(204, 0, 0));
        jLabelWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinner.setText("jLabel18");
        jLabelWinner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonContinue.setBackground(new java.awt.Color(114, 218, 142));
        jButtonContinue.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 24)); // NOI18N
        jButtonContinue.setForeground(new java.awt.Color(0, 0, 0));
        jButtonContinue.setText("Дальше");
        jButtonContinue.addActionListener(this::jButtonNewRound);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanelWin);
        jPanelWin.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(208, 208, 208)
                                                .addComponent(jButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(jLabelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(jButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialogWinner.getContentPane());
        jDialogWinner.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanelFinish.setBackground(new java.awt.Color(255, 204, 255));

        jLabelPlayerWin.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD | Font.ITALIC, 24)); // NOI18N
        jLabelPlayerWin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPlayerWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlayerWin.setText("Победа на вашей стороне");

        jTextFieldPlayerName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPlayerName.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 18)); // NOI18N
        jTextFieldPlayerName.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPlayerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPlayerName.addActionListener(this::jTextField1ActionPerformed);

        jLabelSetPlayerName.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jLabelSetPlayerName.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSetPlayerName.setText("Введите имя своего персонажа для добавления");

        jLabelSetNameForTable.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jLabelSetNameForTable.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSetNameForTable.setText("результата в таблицу рекордов");

        jButtonFinishGame.setBackground(new java.awt.Color(153, 153, 255));
        jButtonFinishGame.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jButtonFinishGame.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFinishGame.setText("Закончить игру");
        jButtonFinishGame.addActionListener(this::jButtonEndGame);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanelFinish);
        jPanelFinish.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonFinishGame)
                                .addGap(14, 14, 14))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(jLabelSetNameForTable))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabelPlayerWin, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabelSetPlayerName))))
                                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabelPlayerWin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSetPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSetNameForTable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFinishGame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialogFinishName.getContentPane());
        jDialogFinishName.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialog2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanelRecordsTable.setBackground(new java.awt.Color(204, 204, 255));

        jLabelRecordsTable.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabelRecordsTable.setForeground(new java.awt.Color(51, 51, 51));
        jLabelRecordsTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRecordsTable.setText("Таблица рекордов");

        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String[]{
                        "Имя", "Количество баллов"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPaneTable.setViewportView(jTableResult);

        jButtonCloseRecordsTable.setBackground(new java.awt.Color(255, 255, 153));
        jButtonCloseRecordsTable.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonCloseRecordsTable.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCloseRecordsTable.setText("Закрыть");
        jButtonCloseRecordsTable.addActionListener(this::jButtonCloseTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanelRecordsTable);
        jPanelRecordsTable.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonCloseRecordsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(160, 160, 160)
                                                        .addComponent(jLabelRecordsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabelRecordsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCloseRecordsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialogTableRecords.getContentPane());
        jDialogTableRecords.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
                jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelRecordsTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
                jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelRecordsTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelWinResult.setBackground(new java.awt.Color(255, 204, 255));

        jLabelWinGame.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD | Font.ITALIC, 24)); // NOI18N
        jLabelWinGame.setForeground(new java.awt.Color(255, 0, 0));
        jLabelWinGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinGame.setText("Победа на вашей стороне");

        jLabelLittleResult.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 14)); // NOI18N
        jLabelLittleResult.setForeground(new java.awt.Color(102, 102, 102));
        jLabelLittleResult.setText("К сожалению, Ваш результат не попал в топ 10");

        jButtonEndGame.setBackground(new java.awt.Color(153, 153, 255));
        jButtonEndGame.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jButtonEndGame.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEndGame.setText("Закончить игру");
        jButtonEndGame.addActionListener(this::jButtonFinishInTop10);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanelWinResult);
        jPanelWinResult.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabelWinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jLabelLittleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(jButtonEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabelWinGame, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabelLittleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButtonEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialogTop10.getContentPane());
        jDialogTop10.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
                jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelWinResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
                jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelWinResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelItems.setBackground(new java.awt.Color(190, 182, 135));

        jLabelBagItems.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 16)); // NOI18N
        jLabelBagItems.setForeground(new java.awt.Color(51, 51, 51));
        jLabelBagItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBagItems.setText("Мешок предметов");

        jRadioFirstItem.setBackground(new java.awt.Color(190, 182, 135));
        jRadioFirstItem.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 12)); // NOI18N
        jRadioFirstItem.setForeground(new java.awt.Color(0, 0, 0));
        jRadioFirstItem.setText("Малое зелье лечение, 0 шт");

        jRadioSecondItem.setBackground(new java.awt.Color(190, 182, 135));
        jRadioSecondItem.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 12)); // NOI18N
        jRadioSecondItem.setForeground(new java.awt.Color(0, 0, 0));
        jRadioSecondItem.setText("Большое зелье лечение, 0 шт");

        jRadioThirdItem.setBackground(new java.awt.Color(190, 182, 135));
        jRadioThirdItem.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 12)); // NOI18N
        jRadioThirdItem.setForeground(new java.awt.Color(0, 0, 0));
        jRadioThirdItem.setText("Крест возрождения, 0 шт");

        jButtonUseItem.setBackground(new java.awt.Color(239, 237, 14));
        jButtonUseItem.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 14)); // NOI18N
        jButtonUseItem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUseItem.setText("Использовать");
        jButtonUseItem.addActionListener(this::jButtonUseItemActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanelItems);
        jPanelItems.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jRadioSecondItem)
                                                        .addComponent(jRadioThirdItem, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRadioFirstItem, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelBagItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(139, 139, 139)
                                                .addComponent(jButtonUseItem)))
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelBagItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jRadioFirstItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioSecondItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioThirdItem)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonUseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialogItems.getContentPane());
        jDialogItems.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
                jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog5Layout.setVerticalGroup(
                jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCantUseItem.setBackground(new java.awt.Color(243, 120, 120));

        jLabelCantUseItem.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 18)); // NOI18N
        jLabelCantUseItem.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCantUseItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantUseItem.setText("Вы не можете использовать ");

        jLabelCantUseItemContinue.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 18)); // NOI18N
        jLabelCantUseItemContinue.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCantUseItemContinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantUseItemContinue.setText("этот предмет");

        jButtonCantUseItemOK.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCantUseItemOK.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 18)); // NOI18N
        jButtonCantUseItemOK.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCantUseItemOK.setText("ОК");
        jButtonCantUseItemOK.addActionListener(this::jButtonCantUseItemActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanelCantUseItem);
        jPanelCantUseItem.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap(82, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                .addComponent(jLabelCantUseItem)
                                                .addGap(58, 58, 58))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                .addComponent(jLabelCantUseItemContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(135, 135, 135))))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButtonCantUseItemOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabelCantUseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCantUseItemContinue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jButtonCantUseItemOK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialogCantUseItem.getContentPane());
        jDialogCantUseItem.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
                jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelCantUseItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog6Layout.setVerticalGroup(
                jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelCantUseItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelCountLocation.setText("Выберите количество локаций");
        jButtonChoseLocation.setText("Начать");
        jButtonChoseLocation.addActionListener(this::jButtonChoseLocationActionPerformed);

        javax.swing.GroupLayout jPanelChoseLocationLayout = new javax.swing.GroupLayout(jPanelChoseLocation);
        jPanelChoseLocation.setLayout(jPanelChoseLocationLayout);
        jPanelChoseLocationLayout.setHorizontalGroup(
                jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                .addGroup(jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addGroup(jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextFieldCountLocation)
                                                        .addComponent(jLabelCountLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(jButtonChoseLocation)))
                                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanelChoseLocationLayout.setVerticalGroup(
                jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelCountLocation)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldCountLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonChoseLocation)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogChoseLocationLayout = new javax.swing.GroupLayout(jDialogChoseLocation.getContentPane());
        jDialogChoseLocation.getContentPane().setLayout(jDialogChoseLocationLayout);
        jDialogChoseLocationLayout.setHorizontalGroup(
                jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelChoseLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogChoseLocationLayout.setVerticalGroup(
                jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 206, Short.MAX_VALUE)
                        .addGroup(jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelChoseLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelStart.setBackground(new java.awt.Color(255, 255, 255));

        jLabelGame.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        jLabelGame.setForeground(new java.awt.Color(204, 204, 0));
        jLabelGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGame.setText("Mortal Kombat");

        jButtonStartGame.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonStartGame.setText("Начать новую игру");
        jButtonStartGame.addActionListener(this::jButtonStartGameActionPerformed);

        jButtonShowRecords.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonShowRecords.setText("Посмотреть таблицу \nрезультатов");
        jButtonShowRecords.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButtonShowRecords.addActionListener(this::jButtonOpenTable);

        jLabelGameImage.setIcon(new javax.swing.ImageIcon("src/main/resources/images/mk.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanelStart);
        jPanelStart.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonShowRecords)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(159, 159, 159)
                                                .addComponent(jLabelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(jLabelGameImage)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelGameImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonShowRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialogChoseLocation.setVisible(true);
        jDialogChoseLocation.setBounds(100, 100, 400, 250);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonChoseLocationActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            game.setNumberOfLocations(Integer.parseInt(jTextFieldCountLocation.getText()));
            if (game.getNumberOfLocations() <= 0 || game.getNumberOfLocations() > 10) {
                throw new Exception();
            }
            jDialogChoseLocation.dispose();

            human = game.NewHuman(jPlayerHPBar);
            enemy = game.NewEnemy(jEnemyImage, jEnemyName, jEnemyDamage, jEnemyHealth, jEnemyHPBar);
            game.change.NewRoundTexts(human, enemy, jPlayerHPBar, jEnemyHPBar,
                    jPlayerPoints, jPlayerExperience, jPlayerLevel, jEnemyLevel, jPlayerHealth, jEnemyHealth, jLabelPlayerDamageValue,
                    jTurnNow, jResult, game.fight.i, items, jRadioFirstItem, jRadioSecondItem, jRadioThirdItem);

            jGamingFrame.setVisible(rootPaneCheckingEnabled);
            jGamingFrame.setSize(1000, 700);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ошибка ввода локаций", "Oшибка", JOptionPane.ERROR_MESSAGE);
            jTextFieldCountLocation.setText("");
        }

    }

    private void jButtonAttack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        game.fight.Hit(human, enemy, 1, jEnemyHealth, jPlayerHealth, jDialogWinner,
                jLabelWinner, game.action, jPlayerHPBar, jEnemyHPBar, jDialogFinishName,
                jDialogTop10, jGamingFrame, game.getResults(), jLabelPlayerWin, jLabelWinGame,
                jTurnNow, jLabelStun, jResult, items, jRadioThirdItem);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDefence(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        game.fight.Hit(human, enemy, 0, jEnemyHealth, jPlayerHealth, jDialogWinner,
                jLabelWinner, game.action, jPlayerHPBar, jEnemyHPBar, jDialogFinishName,
                jDialogTop10, jGamingFrame, game.getResults(), jLabelPlayerWin, jLabelWinGame,
                jTurnNow, jLabelStun, jResult, items, jRadioThirdItem);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonNewRound(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        enemy = game.fight.NewRound(human, jEnemyImage, jPlayerHPBar, jEnemyHPBar,
                jEnemyName, jEnemyDamage, jEnemyHealth, game.action);

        game.change.NewRoundTexts(human, enemy, jPlayerHPBar, jEnemyHPBar,
                jPlayerPoints, jPlayerExperience, jPlayerLevel, jEnemyLevel, jPlayerHealth, jEnemyHealth, jLabelPlayerDamageValue,
                jTurnNow, jResult, game.fight.i, items, jRadioFirstItem, jRadioSecondItem, jRadioThirdItem);

        jDialogWinner.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonEndGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            game.EndGameTop(human, jTextFieldPlayerName, jTableResult);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogFinishName.dispose();
        jTextFieldPlayerName.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonCloseTable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jDialogTableRecords.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonOpenTable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialogTableRecords.setVisible(true);
        jDialogTableRecords.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonFinishInTop10(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jDialogTop10.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonUseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jRadioFirstItem.isSelected()) {
            nameButton = "jRadioButton1";
        }
        if (jRadioSecondItem.isSelected()) {
            nameButton = "jRadioButton2";
        }
        if (jRadioThirdItem.isSelected()) {
            nameButton = "jRadioButton3";
        }
        game.action.UseItem(human, items, nameButton, jDialogCantUseItem, jDialogItems);
        game.action.HP(human, jPlayerHPBar);
        jPlayerHealth.setText(human.getHealth() + "/" + human.getMaxHealth());
        game.change.BagText(items, jRadioFirstItem, jRadioSecondItem, jRadioThirdItem);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jDialogItems.setVisible(true);
        jDialogItems.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonCantUseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jDialogCantUseItem.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTextField jTextFieldCountLocation;
    private javax.swing.JDialog jDialogChoseLocation;
    private javax.swing.JLabel jLabelCountLocation;
    private javax.swing.JButton jButtonChoseLocation;
    private javax.swing.JPanel jPanelChoseLocation;
    private javax.swing.ButtonGroup itemsButtonGroup;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JButton jButtonItems;
    private javax.swing.JButton jButtonCantUseItemOK;
    private javax.swing.JButton jButtonShowRecords;
    private javax.swing.JButton jButtonAttack;
    private javax.swing.JButton jButtonDefence;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonFinishGame;
    private javax.swing.JButton jButtonCloseRecordsTable;
    private javax.swing.JButton jButtonEndGame;
    private javax.swing.JButton jButtonUseItem;
    private javax.swing.JDialog jDialogWinner;
    private javax.swing.JDialog jDialogFinishName;
    private javax.swing.JDialog jDialogTableRecords;
    private javax.swing.JDialog jDialogTop10;
    private javax.swing.JDialog jDialogItems;
    private javax.swing.JDialog jDialogCantUseItem;
    private javax.swing.JFrame jGamingFrame;
    private javax.swing.JLabel jLabelGame;
    private javax.swing.JLabel jEnemyDamage;
    private javax.swing.JLabel jLabelFight;
    private javax.swing.JLabel jPlayerHealth;
    private javax.swing.JLabel jEnemyHealth;
    private javax.swing.JLabel jLabelExperience;
    private javax.swing.JLabel jLabelPoints;
    private javax.swing.JLabel jPlayerExperience;
    private javax.swing.JLabel jPlayerPoints;
    private javax.swing.JLabel jLabelWinner;
    private javax.swing.JLabel jEnemyLevel;
    private javax.swing.JLabel jLabelPlayerIcon;
    private javax.swing.JLabel jLabelPlayerWin;
    private javax.swing.JLabel jLabelSetPlayerName;
    private javax.swing.JLabel jLabelSetNameForTable;
    private javax.swing.JLabel jLabelRecordsTable;
    private javax.swing.JLabel jLabelWinGame;
    private javax.swing.JLabel jLabelLittleResult;
    private javax.swing.JLabel jTurnNow;
    private javax.swing.JLabel jResult;
    private javax.swing.JLabel jLabelPlayerName;
    private javax.swing.JLabel jLabelStun;
    private javax.swing.JLabel jLabelGameImage;
    private javax.swing.JLabel jLabelBagItems;
    private javax.swing.JLabel jLabelCantUseItem;
    private javax.swing.JLabel jLabelCantUseItemContinue;
    private javax.swing.JLabel jEnemyImage;
    private javax.swing.JLabel jEnemyName;
    private javax.swing.JLabel jPlayerLevel;
    private javax.swing.JLabel jLabelEnemyDamage;
    private javax.swing.JLabel jLabelPlayerDamage;
    private javax.swing.JLabel jLabelPlayerDamageValue;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JPanel jPanelGameplay;
    private javax.swing.JPanel jPanelWin;
    private javax.swing.JPanel jPanelFinish;
    private javax.swing.JPanel jPanelRecordsTable;
    private javax.swing.JPanel jPanelWinResult;
    private javax.swing.JPanel jPanelItems;
    private javax.swing.JPanel jPanelCantUseItem;
    private javax.swing.JProgressBar jPlayerHPBar;
    private javax.swing.JProgressBar jEnemyHPBar;
    private javax.swing.JRadioButton jRadioFirstItem;
    private javax.swing.JRadioButton jRadioSecondItem;
    private javax.swing.JRadioButton jRadioThirdItem;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTableResult;
    private javax.swing.JTextField jTextFieldPlayerName;
    // End of variables declaration//GEN-END:variables
}
